### ISSUE TITLE
Username cannot be added to Application Settings in the portal.

### ISSUE THREAD

**Issue by chris31389** [Azure-Samples/azure-devops-release-notes#1]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy to Azure.
> Try to edit Application Settings to add Username

### Any log messages given by the failure
>Failed to update web app settings: ["{\"Code\":\"BadRequest\",\"Message\":\"The data is not valid (Invalid or not allowed environment key name: Username).\",\"Target\":null,\"Details\":[{\"Message\":\"The data is not valid (Invalid or not allowed environment key name: Username).\"},{\"Code\":\"BadRequest\"},{\"ErrorEntity\":{\"ExtendedCode\":\"01019\",\"MessageTemplate\":\"The data is not valid ({0}).\",\"Parameters\":[\"Invalid or not allowed environment key name: Username\"],\"Code\":\"BadRequest\",\"Message\":\"The data is not valid (Invalid or not allowed environment key name: Username).\"}}],\"Innererror\":null}"]

### Expected/desired behavior
> Username is saved

### Mention any other details that might be useful

> Changing the Variable name to DevOps.Username should fix it.

**Comment by paladique** [comment]
Fixed in #2
